runtime: php55
api_version: 3
threadsafe: true

handlers:
- url: /
  static_files: www/index.htm
  upload: www/index.htm
  secure: always
  redirect_http_response_code: 301

- url: /privacy/?
  static_files: www/privacy.htm
  upload: www/privacy.htm
  secure: always
  redirect_http_response_code: 301

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always
  redirect_http_response_code: 301
